LIBNAME ASSGN1 '/home/andrewboschee0/Data';
/*SORT COLUMNS BY ID*/
PROC SORT DATA=ASSGN1.DEMOGRAP;
BY CID;
RUN;

PROC SORT DATA=ASSGN1.CAMPAIGN;
BY CID;
RUN;

PROC SORT DATA=ASSGN1.DEPOSIT;
BY CID;
RUN;

/*LEFT JOIN DEPOSIT AND DEMOGRAPHICS*/
DATA ASSGN1.TRAINING;
MERGE ASSGN1.DEPOSIT(IN=A) ASSGN1.DEMOGRAP(IN=B);
BY CID;
IF A;
RUN;

/*LEFT JOIN TRAINING TABLE WITH CAMPAIGN*/
DATA ASSGN1.COMPLETE;
MERGE ASSGN1.TRAINING(IN=A) ASSGN1.CAMPAIGN(IN=B);
BY CID;
IF A;
RUN;

/*PRINT FIRST 30 ROWS*/
PROC PRINT DATA=ASSGN1.COMPLETE (obs=30);
RUN;

/*TRAINING SET SUMMARY*/
PROC CONTENTS DATA=ASSGN1.COMPLETE;

/*DROP CID AND DURATION*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE (drop = cid duration);
RUN;

PROC FREQ DATA=ASSGN1.COMPLETE;
TABLES EDUCATION JOB MARITAL DEFAULT HOUSING LOAN DEPOSIT POUTCOME ;
RUN;

PROC MEANS DATA=ASSGN1.COMPLETE MEAN MIN MAX P1 P25 P50 P75 P90 P95 P99 NMISS;
VAR AGE CAMPAIGN PDAYS PREVIOUS ;
RUN;

/*substitute yes or string intended to be yes with 1, no with 0 using TRANWRD function*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE;
	LOAN=TRANWRD(LOAN,'yes','1');
	LOAN=TRANWRD(LOAN,'no','0');
	DEFAULT=TRANWRD(DEFAULT,'yes','1');
	DEFAULT=TRANWRD(DEFAULT,'ye','1');
	DEFAULT=TRANWRD(DEFAULT,'no','0');
	DEPOSIT=TRANWRD(DEPOSIT,'yes','1');
	DEPOSIT=TRANWRD(DEPOSIT,'no','0');
run;

/*FILL IN MISSING VALUES WITH PROPER STRINGS*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE;
	IF EDUCATION = '' THEN EDUCATION = 'unknown';
	IF JOB = '' THEN JOB ='unknown';
	IF HOUSING = '' THEN HOUSING = 'missing';
RUN;
PROC PRINT DATA=ASSGN1.COMPLETE (obs=30);
RUN;

/*CREATE DUMMY VARIABLES FOR EACH OUTCOME*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE;
	IF POUTCOME = 'failure' THEN POUTCOME_FAILURE=1;
		ELSE POUTCOME_FAILURE = 0;
	IF POUTCOME = 'success' THEN POUTCOME_SUCCESS=1;
		ELSE POUTCOME_SUCCESS=0;
	IF POUTCOME = 'other' THEN POUTCOME_OTHER =1;
		ELSE POUTCOME_OTHER=0;
	IF POUTCOME = 'unknown' THEN POUTCOME_UNKNOWN=1;
		ELSE POUTCOME_UNKNOWN=0;
RUN;
PROC FREQ DATA= ASSGN1.COMPLETE;
	TABLES POUTCOME_SUCCESS POUTCOME_FAILURE POUTCOME_OTHER POUTCOME_UNKNOWN / LIST;
RUN;

PROC PRINT DATA=ASSGN1.COMPLETE(OBS=30);
RUN;

/*DROP ORIGINAL CATEGORICAL VARIABLE*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE (drop = POUTCOME);
RUN;

/*DROP ONE MEANINGFUL DUMMY VARIABLE*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE (drop = POUTCOME_SUCCESS);
RUN;

PROC MEANS DATA=ASSGN1.COMPLETE MEAN NMISS;
VAR BALANCE;
RUN;
/*ADD MISSING BALANCE COLUMN TO FIND MISSING BALANCES*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE;
	IF BALANCE = '' THEN BALANCE_MISSING=1;
		ELSE BALANCE_MISSING=0;
RUN;
/*INPUT MEAN BALANCE INTO MISSING VALUES OF BALANCE COLUMN*/
DATA ASSGN1.COMPLETE;
	SET ASSGN1.COMPLETE;
	IF BALANCE_MISSING = 1 THEN BALANCE = 1422.90;
RUN;

PROC LOGISTIC DATA = ASSGN1.COMPLETE;
	CLASS JOB MARITAL EDUCATION DEFAULT HOUSING LOAN POUTCOME_FAILURE 
	POUTCOME_OTHER POUTCOME_UNKNOWN BALANCE_MISSING;
	MODEL DEPOSIT=JOB MARITAL EDUCATION DEFAULT HOUSING LOAN BALANCE 
	AGE CAMPAIGN PDAYS PREVIOUS BALANCE_MISSING POUTCOME_FAILURE POUTCOME_OTHER POUTCOME_UNKNOWN/EXPB;
RUN;

